"""initial"""

import sqlalchemy as sa
from alembic import op

revision = "cf7342210e6c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("wave", sa.String(), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("registration_open_at", sa.DateTime(), nullable=True),
        sa.Column("registration_close_at", sa.DateTime(), nullable=True),
        sa.Column("structure_data", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("type IN ('mock', 'ege')", name=op.f("ck_exams_type")),
        sa.CheckConstraint("ends_at >= starts_at", name=op.f("ck_exams_date_order")),
        sa.CheckConstraint(
            "registration_close_at >= registration_open_at",
            name=op.f("ck_exams_registration_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exams")),
    )
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exams_starts_at"), ["starts_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_exams_subject"), ["subject"], unique=False)
        batch_op.create_index(batch_op.f("ix_exams_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_exams_wave"), ["wave"], unique=False)

    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.CheckConstraint(
            "role IN ('admin', 'responsible', 'teacher')", name=op.f("ck_staff_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
        sa.UniqueConstraint("login", name=op.f("uq_staff_login")),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("name_key", sa.String(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("access_code_hash", sa.String(), nullable=True),
        sa.CheckConstraint("grade BETWEEN 1 AND 11", name=op.f("ck_students_grade_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_students_external_id"), ["external_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_students_name_key"), ["name_key"], unique=False)

    op.create_table(
        "participations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("primary_score", sa.Float(), nullable=True),
        sa.Column("test_score", sa.Float(), nullable=True),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('registered', 'attended', 'submitted', 'checked', "
            "'published', 'absent', 'cancelled')",
            name=op.f("ck_participations_status"),
        ),
        sa.CheckConstraint("primary_score >= 0", name=op.f("ck_participations_primary_score")),
        sa.CheckConstraint("test_score >= 0", name=op.f("ck_participations_test_score")),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name=op.f("fk_participations_exam_id_exams")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_participations_student_id_students")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participations")),
        sa.UniqueConstraint("student_id", "exam_id", name=op.f("uq_participations_student_id")),
    )
    with op.batch_alter_table("participations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_participations_exam_id"), ["exam_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_participations_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_participations_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "study_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"], ["staff.id"], name=op.f("fk_study_groups_teacher_id_staff")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_groups")),
        sa.UniqueConstraint("source_name", name=op.f("uq_study_groups_source_name")),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.CheckConstraint("ended_at >= started_at", name=op.f("ck_memberships_date_order")),
        sa.ForeignKeyConstraint(
            ["group_id"], ["study_groups.id"], name=op.f("fk_memberships_group_id_study_groups")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_memberships_student_id_students")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_ended_at"), ["ended_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_student_id"), ["student_id"], unique=False)
        batch_op.create_index(
            "uq_memberships_active",
            ["student_id", "group_id"],
            unique=True,
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_memberships_active",
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_memberships_student_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_group_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_ended_at"))

    op.drop_table("memberships")
    op.drop_table("study_groups")
    with op.batch_alter_table("participations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_participations_student_id"))
        batch_op.drop_index(batch_op.f("ix_participations_status"))
        batch_op.drop_index(batch_op.f("ix_participations_exam_id"))

    op.drop_table("participations")
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_students_name_key"))
        batch_op.drop_index(batch_op.f("ix_students_external_id"))

    op.drop_table("students")
    op.drop_table("staff")
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exams_wave"))
        batch_op.drop_index(batch_op.f("ix_exams_type"))
        batch_op.drop_index(batch_op.f("ix_exams_subject"))
        batch_op.drop_index(batch_op.f("ix_exams_starts_at"))

    op.drop_table("exams")
    # ### end Alembic commands ###
